"""The normalised tender record, and the reference data every source maps onto.

One record shape for every source in the world. A source reader's only job is to
produce these dicts; nothing downstream knows where a tender came from.
"""
from __future__ import annotations

import hashlib
import json
import re
import unicodedata

FIELDS = (
    "id", "source", "source_ref", "url",
    "title", "title_lang", "titles_json",
    "description", "description_lang",
    "buyer_name", "country", "country_name",
    "cpv", "cpv_division", "category",
    "value_amount", "value_currency",
    "procedure", "contract_nature",
    "published_at", "deadline_at",
    "content_hash",
)

# ISO 3166 alpha-3 -> (alpha-2, English name). Covers the EU/EEA plus the countries
# our current and near-term sources publish for. Unknown codes pass through as-is.
# ISO 3166-1: alpha-3 -> (alpha-2, English display name). Generated from the
# Open Knowledge country-codes dataset, with short CLDR forms overridden where
# they were too terse for a page title.
COUNTRIES = {
    "ABW": ("AW", "Aruba"),
    "AFG": ("AF", "Afghanistan"),
    "AGO": ("AO", "Angola"),
    "AIA": ("AI", "Anguilla"),
    "ALA": ("AX", "Åland Islands"),
    "ALB": ("AL", "Albania"),
    "AND": ("AD", "Andorra"),
    "ARE": ("AE", "United Arab Emirates"),
    "ARG": ("AR", "Argentina"),
    "ARM": ("AM", "Armenia"),
    "ASM": ("AS", "American Samoa"),
    "ATA": ("AQ", "Antarctica"),
    "ATF": ("TF", "French Southern Territories"),
    "ATG": ("AG", "Antigua & Barbuda"),
    "AUS": ("AU", "Australia"),
    "AUT": ("AT", "Austria"),
    "AZE": ("AZ", "Azerbaijan"),
    "BDI": ("BI", "Burundi"),
    "BEL": ("BE", "Belgium"),
    "BEN": ("BJ", "Benin"),
    "BES": ("BQ", "Caribbean Netherlands"),
    "BFA": ("BF", "Burkina Faso"),
    "BGD": ("BD", "Bangladesh"),
    "BGR": ("BG", "Bulgaria"),
    "BHR": ("BH", "Bahrain"),
    "BHS": ("BS", "Bahamas"),
    "BIH": ("BA", "Bosnia"),
    "BLM": ("BL", "St. Barthélemy"),
    "BLR": ("BY", "Belarus"),
    "BLZ": ("BZ", "Belize"),
    "BMU": ("BM", "Bermuda"),
    "BOL": ("BO", "Bolivia"),
    "BRA": ("BR", "Brazil"),
    "BRB": ("BB", "Barbados"),
    "BRN": ("BN", "Brunei"),
    "BTN": ("BT", "Bhutan"),
    "BVT": ("BV", "Bouvet Island"),
    "BWA": ("BW", "Botswana"),
    "CAF": ("CF", "Central African Republic"),
    "CAN": ("CA", "Canada"),
    "CCK": ("CC", "Cocos Islands"),
    "CHE": ("CH", "Switzerland"),
    "CHL": ("CL", "Chile"),
    "CHN": ("CN", "China"),
    "CIV": ("CI", "Côte d’Ivoire"),
    "CMR": ("CM", "Cameroon"),
    "COD": ("CD", "Democratic Republic of the Congo"),
    "COG": ("CG", "Republic of the Congo"),
    "COK": ("CK", "Cook Islands"),
    "COL": ("CO", "Colombia"),
    "COM": ("KM", "Comoros"),
    "CPV": ("CV", "Cape Verde"),
    "CRI": ("CR", "Costa Rica"),
    "CUB": ("CU", "Cuba"),
    "CUW": ("CW", "Curaçao"),
    "CXR": ("CX", "Christmas Island"),
    "CYM": ("KY", "Cayman Islands"),
    "CYP": ("CY", "Cyprus"),
    "CZE": ("CZ", "Czechia"),
    "DEU": ("DE", "Germany"),
    "DJI": ("DJ", "Djibouti"),
    "DMA": ("DM", "Dominica"),
    "DNK": ("DK", "Denmark"),
    "DOM": ("DO", "Dominican Republic"),
    "DZA": ("DZ", "Algeria"),
    "ECU": ("EC", "Ecuador"),
    "EGY": ("EG", "Egypt"),
    "ERI": ("ER", "Eritrea"),
    "ESH": ("EH", "Western Sahara"),
    "ESP": ("ES", "Spain"),
    "EST": ("EE", "Estonia"),
    "ETH": ("ET", "Ethiopia"),
    "FIN": ("FI", "Finland"),
    "FJI": ("FJ", "Fiji"),
    "FLK": ("FK", "Falkland Islands"),
    "FRA": ("FR", "France"),
    "FRO": ("FO", "Faroe Islands"),
    "FSM": ("FM", "Micronesia"),
    "GAB": ("GA", "Gabon"),
    "GBR": ("GB", "United Kingdom"),
    "GEO": ("GE", "Georgia"),
    "GGY": ("GG", "Guernsey"),
    "GHA": ("GH", "Ghana"),
    "GIB": ("GI", "Gibraltar"),
    "GIN": ("GN", "Guinea"),
    "GLP": ("GP", "Guadeloupe"),
    "GMB": ("GM", "Gambia"),
    "GNB": ("GW", "Guinea-Bissau"),
    "GNQ": ("GQ", "Equatorial Guinea"),
    "GRC": ("GR", "Greece"),
    "GRD": ("GD", "Grenada"),
    "GRL": ("GL", "Greenland"),
    "GTM": ("GT", "Guatemala"),
    "GUF": ("GF", "French Guiana"),
    "GUM": ("GU", "Guam"),
    "GUY": ("GY", "Guyana"),
    "HKG": ("HK", "Hong Kong"),
    "HMD": ("HM", "Heard & McDonald Islands"),
    "HND": ("HN", "Honduras"),
    "HRV": ("HR", "Croatia"),
    "HTI": ("HT", "Haiti"),
    "HUN": ("HU", "Hungary"),
    "IDN": ("ID", "Indonesia"),
    "IMN": ("IM", "Isle of Man"),
    "IND": ("IN", "India"),
    "IOT": ("IO", "British Indian Ocean Territory"),
    "IRL": ("IE", "Ireland"),
    "IRN": ("IR", "Iran"),
    "IRQ": ("IQ", "Iraq"),
    "ISL": ("IS", "Iceland"),
    "ISR": ("IL", "Israel"),
    "ITA": ("IT", "Italy"),
    "JAM": ("JM", "Jamaica"),
    "JEY": ("JE", "Jersey"),
    "JOR": ("JO", "Jordan"),
    "JPN": ("JP", "Japan"),
    "KAZ": ("KZ", "Kazakhstan"),
    "KEN": ("KE", "Kenya"),
    "KGZ": ("KG", "Kyrgyzstan"),
    "KHM": ("KH", "Cambodia"),
    "KIR": ("KI", "Kiribati"),
    "KNA": ("KN", "St. Kitts & Nevis"),
    "KOR": ("KR", "South Korea"),
    "KWT": ("KW", "Kuwait"),
    "LAO": ("LA", "Laos"),
    "LBN": ("LB", "Lebanon"),
    "LBR": ("LR", "Liberia"),
    "LBY": ("LY", "Libya"),
    "LCA": ("LC", "St. Lucia"),
    "LIE": ("LI", "Liechtenstein"),
    "LKA": ("LK", "Sri Lanka"),
    "LSO": ("LS", "Lesotho"),
    "LTU": ("LT", "Lithuania"),
    "LUX": ("LU", "Luxembourg"),
    "LVA": ("LV", "Latvia"),
    "MAC": ("MO", "Macao"),
    "MAF": ("MF", "St. Martin"),
    "MAR": ("MA", "Morocco"),
    "MCO": ("MC", "Monaco"),
    "MDA": ("MD", "Moldova"),
    "MDG": ("MG", "Madagascar"),
    "MDV": ("MV", "Maldives"),
    "MEX": ("MX", "Mexico"),
    "MHL": ("MH", "Marshall Islands"),
    "MKD": ("MK", "North Macedonia"),
    "MLI": ("ML", "Mali"),
    "MLT": ("MT", "Malta"),
    "MMR": ("MM", "Myanmar"),
    "MNE": ("ME", "Montenegro"),
    "MNG": ("MN", "Mongolia"),
    "MNP": ("MP", "Northern Mariana Islands"),
    "MOZ": ("MZ", "Mozambique"),
    "MRT": ("MR", "Mauritania"),
    "MSR": ("MS", "Montserrat"),
    "MTQ": ("MQ", "Martinique"),
    "MUS": ("MU", "Mauritius"),
    "MWI": ("MW", "Malawi"),
    "MYS": ("MY", "Malaysia"),
    "MYT": ("YT", "Mayotte"),
    "NAM": ("NA", "Namibia"),
    "NCL": ("NC", "New Caledonia"),
    "NER": ("NE", "Niger"),
    "NFK": ("NF", "Norfolk Island"),
    "NGA": ("NG", "Nigeria"),
    "NIC": ("NI", "Nicaragua"),
    "NIU": ("NU", "Niue"),
    "NLD": ("NL", "Netherlands"),
    "NOR": ("NO", "Norway"),
    "NPL": ("NP", "Nepal"),
    "NRU": ("NR", "Nauru"),
    "NZL": ("NZ", "New Zealand"),
    "OMN": ("OM", "Oman"),
    "PAK": ("PK", "Pakistan"),
    "PAN": ("PA", "Panama"),
    "PCN": ("PN", "Pitcairn"),
    "PER": ("PE", "Peru"),
    "PHL": ("PH", "Philippines"),
    "PLW": ("PW", "Palau"),
    "PNG": ("PG", "Papua New Guinea"),
    "POL": ("PL", "Poland"),
    "PRI": ("PR", "Puerto Rico"),
    "PRK": ("KP", "North Korea"),
    "PRT": ("PT", "Portugal"),
    "PRY": ("PY", "Paraguay"),
    "PSE": ("PS", "Palestine"),
    "PYF": ("PF", "French Polynesia"),
    "QAT": ("QA", "Qatar"),
    "REU": ("RE", "Réunion"),
    "ROU": ("RO", "Romania"),
    "RUS": ("RU", "Russia"),
    "RWA": ("RW", "Rwanda"),
    "SAU": ("SA", "Saudi Arabia"),
    "SDN": ("SD", "Sudan"),
    "SEN": ("SN", "Senegal"),
    "SGP": ("SG", "Singapore"),
    "SGS": ("GS", "South Georgia & South Sandwich Islands"),
    "SHN": ("SH", "St. Helena"),
    "SJM": ("SJ", "Svalbard & Jan Mayen"),
    "SLB": ("SB", "Solomon Islands"),
    "SLE": ("SL", "Sierra Leone"),
    "SLV": ("SV", "El Salvador"),
    "SMR": ("SM", "San Marino"),
    "SOM": ("SO", "Somalia"),
    "SPM": ("PM", "St. Pierre & Miquelon"),
    "SRB": ("RS", "Serbia"),
    "SSD": ("SS", "South Sudan"),
    "STP": ("ST", "São Tomé & Príncipe"),
    "SUR": ("SR", "Suriname"),
    "SVK": ("SK", "Slovakia"),
    "SVN": ("SI", "Slovenia"),
    "SWE": ("SE", "Sweden"),
    "SWZ": ("SZ", "Eswatini"),
    "SXM": ("SX", "Sint Maarten"),
    "SYC": ("SC", "Seychelles"),
    "SYR": ("SY", "Syria"),
    "TCA": ("TC", "Turks & Caicos Islands"),
    "TCD": ("TD", "Chad"),
    "TGO": ("TG", "Togo"),
    "THA": ("TH", "Thailand"),
    "TJK": ("TJ", "Tajikistan"),
    "TKL": ("TK", "Tokelau"),
    "TKM": ("TM", "Turkmenistan"),
    "TLS": ("TL", "Timor-Leste"),
    "TON": ("TO", "Tonga"),
    "TTO": ("TT", "Trinidad & Tobago"),
    "TUN": ("TN", "Tunisia"),
    "TUR": ("TR", "Türkiye"),
    "TUV": ("TV", "Tuvalu"),
    "TWN": ("TW", "Taiwan"),
    "TZA": ("TZ", "Tanzania"),
    "UGA": ("UG", "Uganda"),
    "UKR": ("UA", "Ukraine"),
    "UMI": ("UM", "U.S. Outlying Islands"),
    "URY": ("UY", "Uruguay"),
    "USA": ("US", "United States"),
    "UZB": ("UZ", "Uzbekistan"),
    "VAT": ("VA", "Vatican City"),
    "VCT": ("VC", "St. Vincent & Grenadines"),
    "VEN": ("VE", "Venezuela"),
    "VGB": ("VG", "British Virgin Islands"),
    "VIR": ("VI", "U.S. Virgin Islands"),
    "VNM": ("VN", "Vietnam"),
    "VUT": ("VU", "Vanuatu"),
    "WLF": ("WF", "Wallis & Futuna"),
    "WSM": ("WS", "Samoa"),
    "YEM": ("YE", "Yemen"),
    "ZAF": ("ZA", "South Africa"),
    "ZMB": ("ZM", "Zambia"),
    "ZWE": ("ZW", "Zimbabwe"),
}

# Normalised country name -> alpha-2, for sources that publish names, not codes.
# Includes ISO display names, official names, and the spellings the World Bank
# and others actually use.
COUNTRY_NAMES = {
    "afghanistan": "AF",
    "aland islands": "AX",
    "albania": "AL",
    "algeria": "DZ",
    "american samoa": "AS",
    "andorra": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctica": "AQ",
    "antigua and barbuda": "AG",
    "antigua barbuda": "AG",
    "argentina": "AR",
    "armenia": "AM",
    "aruba": "AW",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bhutan": "BT",
    "bolivia": "BO",
    "bolivia plurinational state of": "BO",
    "bonaire sint eustatius and saba": "BQ",
    "bosnia": "BA",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "bouvet island": "BV",
    "brazil": "BR",
    "british indian ocean territory": "IO",
    "british virgin islands": "VG",
    "brunei": "BN",
    "brunei darussalam": "BN",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burma": "MM",
    "burundi": "BI",
    "cabo verde": "CV",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "cape verde": "CV",
    "caribbean netherlands": "BQ",
    "cayman islands": "KY",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "china hong kong special administrative region": "HK",
    "china macao special administrative region": "MO",
    "christmas island": "CX",
    "cocos islands": "CC",
    "cocos keeling islands": "CC",
    "colombia": "CO",
    "comoros": "KM",
    "congo": "CG",
    "congo brazzaville": "CG",
    "congo dem rep": "CD",
    "congo democratic republic of": "CD",
    "congo kinshasa": "CD",
    "congo rep": "CG",
    "cook islands": "CK",
    "costa rica": "CR",
    "cote d ivoire": "CI",
    "cote divoire": "CI",
    "croatia": "HR",
    "cuba": "CU",
    "curacao": "CW",
    "cyprus": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "democratic people s republic of korea": "KP",
    "democratic republic of congo": "CD",
    "democratic republic of the congo": "CD",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic": "DO",
    "drc": "CD",
    "east timor": "TL",
    "ecuador": "EC",
    "egypt": "EG",
    "egypt arab republic of": "EG",
    "el salvador": "SV",
    "england": "GB",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "eswatini": "SZ",
    "ethiopia": "ET",
    "falkland islands": "FK",
    "faroe islands": "FO",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    "french southern territories": "TF",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "great britain": "GB",
    "greece": "GR",
    "greenland": "GL",
    "grenada": "GD",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guernsey": "GG",
    "guinea": "GN",
    "guinea bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "heard island and mcdonald islands": "HM",
    "heard mcdonald islands": "HM",
    "holland": "NL",
    "holy see": "VA",
    "honduras": "HN",
    "hong kong": "HK",
    "hong kong sar china": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iran islamic republic of": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "isle of man": "IM",
    "israel": "IL",
    "italy": "IT",
    "ivory coast": "CI",
    "jamaica": "JM",
    "japan": "JP",
    "jersey": "JE",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "korea rep": "KR",
    "korea republic of": "KR",
    "kosovo": "XK",
    "kuwait": "KW",
    "kyrgyz republic": "KG",
    "kyrgyzstan": "KG",
    "lao pdr": "LA",
    "lao people s democratic republic": "LA",
    "lao peoples democratic republic": "LA",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "macao": "MO",
    "macao sar china": "MO",
    "macedonia": "MK",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "marshall islands": "MH",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mayotte": "YT",
    "mexico": "MX",
    "micronesia": "FM",
    "micronesia fed sts": "FM",
    "micronesia federated states of": "FM",
    "moldova": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "montserrat": "MS",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "myanmar burma": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "netherlands": "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "niue": "NU",
    "norfolk island": "NF",
    "north korea": "KP",
    "north macedonia": "MK",
    "northern mariana islands": "MP",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "palestine": "PS",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "pitcairn": "PN",
    "poland": "PL",
    "portugal": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "republic of congo": "CG",
    "republic of korea": "KR",
    "republic of moldova": "MD",
    "republic of the congo": "CG",
    "reunion": "RE",
    "romania": "RO",
    "russia": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "saint barthelemy": "BL",
    "saint helena": "SH",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint martin french part": "MF",
    "saint pierre and miquelon": "PM",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "sao tome principe": "ST",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "sint maarten": "SX",
    "sint maarten dutch part": "SX",
    "slovak republic": "SK",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south georgia and the south sandwich islands": "GS",
    "south georgia south sandwich islands": "GS",
    "south korea": "KR",
    "south sudan": "SS",
    "spain": "ES",
    "sri lanka": "LK",
    "st barthelemy": "BL",
    "st helena": "SH",
    "st kitts and nevis": "KN",
    "st kitts nevis": "KN",
    "st lucia": "LC",
    "st martin": "MF",
    "st pierre miquelon": "PM",
    "st vincent and the grenadines": "VC",
    "st vincent grenadines": "VC",
    "state of palestine": "PS",
    "sudan": "SD",
    "suriname": "SR",
    "svalbard and jan mayen islands": "SJ",
    "svalbard jan mayen": "SJ",
    "swaziland": "SZ",
    "sweden": "SE",
    "switzerland": "CH",
    "syria": "SY",
    "syrian arab republic": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thailand": "TH",
    "timor leste": "TL",
    "togo": "TG",
    "tokelau": "TK",
    "tonga": "TO",
    "trinidad and tobago": "TT",
    "trinidad tobago": "TT",
    "tunisia": "TN",
    "turkiye": "TR",
    "turkmenistan": "TM",
    "turks and caicos islands": "TC",
    "turks caicos islands": "TC",
    "tuvalu": "TV",
    "u s outlying islands": "UM",
    "u s virgin islands": "VI",
    "uganda": "UG",
    "uk": "GB",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "united kingdom of great britain and northern ireland": "GB",
    "united republic of tanzania": "TZ",
    "united states": "US",
    "united states minor outlying islands": "UM",
    "united states of america": "US",
    "united states virgin islands": "VI",
    "uruguay": "UY",
    "us": "US",
    "usa": "US",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "vatican city": "VA",
    "venezuela": "VE",
    "venezuela bolivarian republic of": "VE",
    "viet nam": "VN",
    "vietnam": "VN",
    "wallis and futuna islands": "WF",
    "wallis futuna": "WF",
    "west bank and gaza": "PS",
    "western sahara": "EH",
    "yemen": "YE",
    "yemen republic of": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW",
}


_NAME_FALLBACK = None


def _normalise_name(text):
    """Fold accents, quotes and punctuation so "Cote d'Ivoire" finds "Côte d’Ivoire"."""
    text = unicodedata.normalize("NFKD", str(text))
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = text.replace("\u2019", "'").casefold()
    text = "".join(c if (c.isalnum() or c == " ") else " " for c in text)
    text = " ".join(text.split())
    return text[4:] if text.startswith("the ") else text


def country_by_name(name):
    """Look up a country from the name a source printed -> (alpha2, display name)."""
    if not name:
        return (None, None)
    key = _normalise_name(name)
    code = COUNTRY_NAMES.get(key)
    if not code and "," in str(name):
        code = COUNTRY_NAMES.get(_normalise_name(str(name).split(",")[0]))
    if not code:
        return (None, None)
    for alpha2, display in COUNTRIES.values():
        if alpha2 == code:
            return (alpha2, display)
    return (code, str(name).strip())

# CPV divisions: the first two digits of the EU Common Procurement Vocabulary.
# This is our master category taxonomy - other sources' codes map onto it.
# The official vocabulary is published in 24 languages, which is where the
# multilingual category names come from in Phase 2.
CPV_DIVISIONS = {
    "03": "Agriculture, farming, fishing and forestry",
    "09": "Petroleum, fuel, electricity and other energy",
    "14": "Mining, metals and minerals",
    "15": "Food, beverages and tobacco",
    "16": "Agricultural machinery",
    "18": "Clothing, footwear and luggage",
    "19": "Leather, textiles, plastics and rubber",
    "22": "Printed matter and related products",
    "24": "Chemicals",
    "30": "Office and computing machinery",
    "31": "Electrical machinery and apparatus",
    "32": "Radio, television and communications equipment",
    "33": "Medical equipment, pharmaceuticals and personal care",
    "34": "Transport equipment",
    "35": "Security, firefighting, police and defence equipment",
    "37": "Musical instruments, sport goods, games and toys",
    "38": "Laboratory, optical and precision equipment",
    "39": "Furniture, furnishings and cleaning products",
    "41": "Collected and purified water",
    "42": "Industrial machinery",
    "43": "Machinery for mining, quarrying and construction",
    "44": "Construction structures, materials and products",
    "45": "Construction work",
    "48": "Software packages and information systems",
    "50": "Repair and maintenance services",
    "51": "Installation services",
    "55": "Hotel, restaurant and retail trade services",
    "60": "Transport services",
    "63": "Supporting transport services, travel agency services",
    "64": "Postal and telecommunications services",
    "65": "Public utilities",
    "66": "Financial and insurance services",
    "70": "Real estate services",
    "71": "Architectural, construction and engineering services",
    "72": "IT services, consulting and software development",
    "73": "Research and development services",
    "75": "Administration, defence and social security services",
    "76": "Services related to the oil and gas industry",
    "77": "Agricultural, forestry and horticultural services",
    "79": "Business services: law, marketing, consulting and recruitment",
    "80": "Education and training services",
    "85": "Health and social work services",
    "90": "Sewage, refuse, cleaning and environmental services",
    "92": "Recreational, cultural and sporting services",
    "98": "Other community, social and personal services",
}

# ISO 639-2/B (what TED uses) -> ISO 639-1, for page language codes.
LANG3_TO_2 = {
    "bul": "bg", "ces": "cs", "dan": "da", "deu": "de", "ell": "el", "eng": "en",
    "est": "et", "fin": "fi", "fra": "fr", "gle": "ga", "hrv": "hr", "hun": "hu",
    "ita": "it", "lav": "lv", "lit": "lt", "mlt": "mt", "nld": "nl", "pol": "pl",
    "por": "pt", "ron": "ro", "slk": "sk", "slv": "sl", "spa": "es", "swe": "sv",
    "ukr": "uk", "rus": "ru", "ara": "ar", "zho": "zh", "nor": "no", "isl": "is",
    "tur": "tr", "srp": "sr", "mkd": "mk", "sqi": "sq", "kat": "ka", "jpn": "ja",
    "kor": "ko", "vie": "vi", "ind": "id", "tha": "th", "hin": "hi", "ben": "bn",
}

_WS = re.compile(r"\s+")


def clean(text, limit=None):
    """Collapse whitespace, strip, optionally truncate on a word boundary."""
    if not text:
        return None
    text = _WS.sub(" ", str(text)).strip()
    if not text:
        return None
    if limit and len(text) > limit:
        text = text[:limit].rsplit(" ", 1)[0] + "…"
    return text


def country_of(code):
    """Accept alpha-2 or alpha-3, return (alpha2, English name)."""
    if not code:
        return (None, None)
    code = str(code).strip().upper()
    if code in COUNTRIES:
        return COUNTRIES[code]
    if len(code) == 2:
        for a2, name in COUNTRIES.values():
            if a2 == code:
                return (a2, name)
        return (code, code)
    return (code[:2], code)


def category_of(cpv):
    """CPV code -> (division, English label)."""
    if not cpv:
        return (None, None)
    division = str(cpv).strip()[:2]
    return (division, CPV_DIVISIONS.get(division))


def lang2(code):
    if not code:
        return None
    code = str(code).strip().lower()
    return LANG3_TO_2.get(code, code[:2])


def make(**kw):
    """Build a record, filling defaults and computing the change hash.

    The hash covers the fields a reader would notice changing, so an unchanged
    notice re-fetched next hour does not count as an update.
    """
    rec = {f: kw.get(f) for f in FIELDS}
    titles = kw.get("titles") or {}
    rec["titles_json"] = json.dumps(titles, ensure_ascii=False, sort_keys=True) if titles else None
    material = "|".join(str(rec.get(f) or "") for f in (
        "title", "titles_json", "description", "description_lang", "title_lang",
        "buyer_name", "country", "cpv", "value_amount", "value_currency",
        "deadline_at", "url"))
    rec["content_hash"] = hashlib.sha1(material.encode("utf-8")).hexdigest()[:16]
    return rec


def validate(rec):
    """Return a list of problems. A record with problems is dropped, not published."""
    problems = []
    if not rec.get("id"):
        problems.append("no id")
    if not rec.get("title"):
        problems.append("no title")
    if not rec.get("url"):
        problems.append("no url")
    if not rec.get("country"):
        problems.append("no country")
    return problems
