#!/usr/bin/env python3
"""Regenerate web/lib/i18n-data.php - category and country names per language.

    python3 tools/build-i18n.py

Category names are the European Union's official CPV wording, pulled from the
eForms SDK codelist, so a Polish reader sees the phrase their own national
portal uses rather than our translation of an English label. Country names come
from CLDR via the country-list project.

Run this when adding a language to LANGS, then commit the generated file.
"""
from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import requests

LANGS = ["en", "de", "fr", "es", "it", "pl", "pt", "nl"]

CPV_SOURCE = "https://raw.githubusercontent.com/OP-TED/eForms-SDK/develop/codelists/cpv.gc"
COUNTRY_SOURCE = "https://raw.githubusercontent.com/umpirsky/country-list/master/data/{lang}/country.json"

# CPV labels are keyed by ISO 639-2/B in the codelist.
CPV_COLUMNS = {"en": "eng", "de": "deu", "fr": "fra", "es": "spa", "it": "ita",
               "pl": "pol", "pt": "por", "nl": "nld", "ro": "ron", "cs": "ces", "sv": "swe"}

OUTPUT = Path(__file__).resolve().parent.parent / "web" / "lib" / "i18n-data.php"


def cpv_divisions(cache: Path):
    if not cache.exists():
        print("downloading the CPV codelist (~32 MB)")
        cache.write_bytes(requests.get(CPV_SOURCE, timeout=300).content)

    divisions = {}
    for _, element in ET.iterparse(cache, events=("end",)):
        if not element.tag.endswith("Row"):
            continue
        row = {}
        for value in element:
            column = value.get("ColumnRef")
            simple = value.find("SimpleValue")
            if column and simple is not None and simple.text:
                row[column] = simple.text.strip()
        code = row.get("code", "")
        if len(code) == 8 and code.endswith("000000"):
            labels = {}
            for lang in LANGS:
                text = row.get(f"{CPV_COLUMNS[lang]}_label")
                if not text and lang == "en":
                    text = row.get("Name")
                if text:
                    labels[lang] = text
            if labels:
                divisions[code[:2]] = labels
        element.clear()
    return divisions


def country_names():
    names = {}
    for lang in LANGS:
        names[lang] = requests.get(COUNTRY_SOURCE.format(lang=lang), timeout=60).json()
        print(f"  {lang}: {len(names[lang])} countries")
    return names


def main():
    cache = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/cpv.gc")
    divisions = cpv_divisions(cache)
    print(f"  CPV divisions: {len(divisions)}")
    countries = country_names()

    lines = [
        "<?php",
        "/**",
        " * Multilingual reference data. Generated by tools/build-i18n.py - do not edit.",
        " *",
        " * Category names are the European Union's own CPV wording from the official",
        " * codelist, so a reader sees the phrase their national portal uses. Country",
        " * names come from CLDR.",
        " */",
        "",
        "declare(strict_types=1);",
        "",
        "const OFT_CPV_DIVISIONS = [",
    ]
    for division in sorted(divisions):
        labels = divisions[division]
        parts = ", ".join(
            f"'{lang}' => " + json.dumps(labels[lang], ensure_ascii=False)
            for lang in LANGS if lang in labels
        )
        lines.append(f"    '{division}' => [{parts}],")
    lines += ["];", "", "const OFT_COUNTRY_NAMES = ["]
    for code in sorted(countries["en"]):
        parts = []
        for lang in LANGS:
            name = countries.get(lang, {}).get(code)
            # Only store a translation that differs from English.
            if name and (lang == "en" or name != countries["en"].get(code)):
                parts.append(f"'{lang}' => " + json.dumps(name, ensure_ascii=False))
        if parts:
            lines.append(f"    '{code}' => [{', '.join(parts)}],")
    lines += ["];", ""]

    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
